spring:
  application:
    name: notification-server

  datasource:
    url: jdbc:mysql://localhost:3306/notification
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  #    url: jdbc:h2:mem:test
#    driverClassName: org.h2.Driver
#    username: sa
#    password:

  #  datasource:
  #    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:tcp://localhost/~/dev/h2/db/coupon
  #    username: sa
  #    password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true